### ISSUE TITLE
own implementation session storage

### ISSUE THREAD

**Issue by Sclaw** [agrafix/Spock#114]
Is there any way to be able to manage cookie that sending session manager? 
I created own session storage. But after login and redirecting to another page, session manager send anew created cookie that different with saving one it database?

**Comment by agrafix** [comment]
Can you provide some code?

**Comment by Sclaw** [comment]
https://gist.github.com/Sclaw/e05535dae41d389b3f3cb79a0edded73
It seems to me that my issue is similar to one with number #100 
All works ok instead of cookie

**Comment by agrafix** [comment]
I think your `ss_store` is wrong, because it does not always store the session. You need to store all sessions that you recieve there, otherwise a new session is generated.

**Comment by Sclaw** [comment]
thanks a lot
