### ISSUE TITLE
Need documentation like Playframework docs (https://www.playframework.com/documentation/2.5.x/Home)

### ISSUE THREAD

**Issue by pamu** [agrafix/Spock#115]
My company want to use Haskell instead of Scala. We use playframework a lot and We are trying to give Haskell Web programming a Shot. If we are happy with it. We would like to migrate all of our codebase to Haskell from Scala. We use micro service architecture, So, we are thinking of using Spock. But there is no proper documentation on the internet. It is so frustrating coming from Playframework ecosystem. Play has beautiful documentation (https://www.playframework.com/documentation/2.5.x/Home). 

All I see is old documentation which is not complete and absolutely not useful. I don't think any framework will be useful without proper documentation or tutorials. I strongly recommend good, complete  and latest documentation. All my enthusiasm for Haskell got killed after seeing the how bad the documentation is for web frameworks in Haskell. This way Haskell will always be the language few people use and will not grow.

**Comment by agrafix** [comment]
Thanks for the feedback. I'm sorry that you find Spock "frustrating", but as you know it is an open source project and I am working on it more or less in my limited free time. I currently do not have the time to write in depth tutorials.

On the other hand, your comment is not very constructive. There are so many Spock example projects here on Github ([Github search shows more than 572 files](https://github.com/search?l=Haskell&q=import+Web.Spock&type=Code&utf8=%E2%9C%93)!!) that you can look at and try to work with and then you can easily answer concrete questions that I will happily answer. Just saying that this is all bad is not helpful and shows zero effort on your side.
