### ISSUE TITLE
instance of MonadBaseControl and MonadTransControl for ActionCtxT

### ISSUE THREAD

**Issue by cdepillabout** [agrafix/Spock#116]
Would you consider adding instances of [`MonadTransControl`](https://hackage.haskell.org/package/monad-control-1.0.1.0/docs/Control-Monad-Trans-Control.html#t:MonadTransControl) and [`MonadBaseControl`](https://hackage.haskell.org/package/monad-control-1.0.1.0/docs/Control-Monad-Trans-Control.html#t:MonadBaseControl) for `ActionCtxT`?

Since `ActionCtxT` is just a [newtype around](https://hackage.haskell.org/package/Spock-core-0.12.0.0/docs/src/Web-Spock-Internal-Wire.html#ActionCtxT) ErrorT and RWST, it should be relatively easy to add instances for `MonadTransControl` and `MonadBaseControl`.

It looks like `Spock-core` doesn't already have a dependency on [monad-control](https://hackage.haskell.org/package/monad-control-1.0.1.0) (but Spock does), so this would require adding `monad-control` as a dependency to Spock-core

If you don't want to do that, would you consider exporting the constructor for ActionCtxT (possibly in an `Internal` module) so that users could write orphan instances for `MonadTransControl` and `MonadBaseControl`?

Let me know how you feel and I'll send a PR.

**Comment by agrafix** [comment]
Sounds good of adding the dependency and class instance to Spock-core.

**Comment by cdepillabout** [comment]
Okay, sounds good.  I'll send a PR adding instances for `MonadTransControl` and `MonadBaseControl` to `ActionCtxT`.

**Comment by agrafix** [comment]
Cool, thanks :-)
