### ISSUE TITLE
Routes that match with any HTTP method

### ISSUE THREAD

**Issue by redneb** [agrafix/Spock#121]
Hi, is there a way to add a route that matches regardless of the HTTP method used? `scotty` has `matchAny`. It would also be nice to be able to find out what method was actually used.

**Comment by agrafix** [comment]
We currently don't have that in Spock as we have a separate "routing table" per method. You can still implement this combinator easily by iterating over all possible methods and wiring them up. Something like:

```haskell
hookMethodAny path handler =
    forM_ [minBound..maxBound] $ \myMethod ->
    hookRoute myMethod path $ handler myMethod
```

**Comment by redneb** [comment]
Yeah, this is what I do currently. I was hopping for something more general, although I suspect that my application (which simply forwards requests to another server) will not encounter any nonstandard HTTP methods.

**Comment by redneb** [comment]
Another application that I had in mind, is the `notFound` route that `scotty` offers. Is there some other sensible way to implement this in `Spock`?

**Comment by agrafix** [comment]
Yes, you can use the error handler of [SpockCfg](http://hackage.haskell.org/package/Spock-0.12.0.0/docs/Web-Spock-Config.html#t:SpockCfg), but you currently only get the `Status`. This can easily be extended if you are up for a PR :-)
