### ISSUE TITLE
Couldn't match type ‘BaseBackend ()’ with ‘SqlBackend’ in Building a REST API Tutorial

### ISSUE THREAD

**Issue by montonero** [agrafix/Spock#127]
Tutorial https://www.spock.li/tutorials/rest-api does not compile due to the following error:
• Couldn't match type ‘BaseBackend ()’ with ‘SqlBackend’
    arising from a use of ‘createSqlitePool’

**Comment by agrafix** [comment]
@brynedwards could you take a look?

**Comment by brynedwards** [comment]
Complete code examples are [here](https://github.com/brynedwards/spock-tutorials/tree/9076c2e0f887dab0bd1758b937d630cdcb9555df/rest-api), all of which compile. If you include your code I could have a look at it, or you could compare your code with the examples.

**Comment by montonero** [comment]
My bad. Samples work perfectly. Many thanks!
