### ISSUE TITLE
Setting CORS header 

### ISSUE THREAD

**Issue by montonero** [agrafix/Spock#129]
First, thanks for the great framework - I really enjoy using Spock!
Although, as have been mentioned elsewhere lack of documentation of advanced features is frustrating.
For instance, I'd like to be able to set "Access-Control-Allow-Origin: *" response header - how is that possible?

**Comment by agrafix** [comment]
I think a good idea is to use a [prehook](http://hackage.haskell.org/package/Spock-0.12.0.0/docs/Web-Spock.html#v:prehook) in combination with [setHeader](http://hackage.haskell.org/package/Spock-core-0.12.0.0/docs/Web-Spock-Action.html#v:setHeader).

Something like this should work:
```haskell
corsHeader =
  do ctx <- getContext
       setHeader "Access-Control-Allow-Origin" "*"
       pure ctx

myApp =
  prehook corsHeader $
  do get ("my" <//> "cool" <//> "path") $ ...
```

**Comment by cstrahan** [comment]
I think you want to do something more like this (using `hookAny`):

```haskell
corsHeader =
  do ctx <- getContext
     setHeader "Access-Control-Allow-Origin" "*"
     setHeader "Access-Control-Allow-Headers" "Content-Type"
     pure ctx

myApp =
  do hookAny OPTIONS (\path -> corsHeader)
     get ("my" <//> "cool" <//> "path") $ ...
```

That's what I used in a recent app.
