### ISSUE TITLE
tutorial seems outdated.

### ISSUE THREAD

**Issue by hanjoosten** [agrafix/Spock#131]
I followed the instructions from the [tutorial](https://www.spock.li/tutorial/), and then I ran into:

~~~~
PS C:\Users\hjo20125\git\spockSandbox\Spock-example> stack build --fast --pedantic

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for Spock-example-0.1.0.0:
    Spock-0.10.0.1 must match >=0.11 (latest applicable is 0.12.0.0)
needed since Spock-example-0.1.0.0 is a build target.

Plan construction failed.
PS C:\Users\hjo20125\git\spockSandbox\Spock-example>
~~~~

It seems that Spock is on stackage now, so there is probably no need to have a modified stack.yml any longer. The dependencies seem to be correct without modifying stack.yml

**Comment by agrafix** [comment]
It's probably only needed to bump the resolver and remove the pinned git repos. Would you like to send a PR for that?

**Comment by hanjoosten** [comment]
There is no need to modify the resolver at all. Out of the box the current resolver will be included with stack new. Assuming you will keep stackage up to date with the master of spock, that should be good enough.

**Comment by agrafix** [comment]
Thanks
