### ISSUE TITLE
Spock not generating new sessionId

### ISSUE THREAD

**Issue by ohri-anurag** [agrafix/Spock#141]
Hi,

It seems that Spock is not generating a new session Id for the same browser, even when the browser is restarted.

The issue can be reproduced in the [Getting Started example](https://www.spock.li/tutorials/getting-started) by printing out the session id whenever root is accessed.

Is there something I'm missing or some setting that I can use? Any help would be greatly appreciated.

Thanks

**Comment by ohri-anurag** [comment]
It seems that browsers nowadays don't clear the session cookie when they are closed. That was causing Spock to reuse the previously generated session id.

**Comment by agrafix** [comment]
You can generate new session IDs using: http://hackage.haskell.org/package/Spock-0.12.0.0/docs/Web-Spock-SessionActions.html#v:sessionRegenerateId
