### ISSUE TITLE
cookie domain for spocksession cookie 

### ISSUE THREAD

**Issue by gurgl** [agrafix/Spock#145]
Hi

I have a little website that uses 2 domains: _example.com_ and _subdomain.example.com_. I've gathered I could add "domain" to the cookie header, in HTTP terms, to make both domains use the same cookie. Looking at the code of Spock it looks hard to change defaultCookieConfig, where this property is read. That is what the SessionManager uses for generating the default spocksession cookie it appears. Do you see a simple way of changing the cookie domain for all requests? 

And please tell if this idea is bad, to begin with? Should one leave the spocksession alone or something? It looks as if it is what is used for the Spock (non Spock-Core) resource config.

**Comment by agrafix** [comment]
Hey! It feels reasonable to extend `SessionCfg` ( http://hackage.haskell.org/package/Spock-0.12.0.0/docs/Web-Spock-Config.html#t:SessionCfg ) for this purpose. Are you up for a PR for this? :)
