### ISSUE TITLE
Please make it clear what the status of Spock is

### ISSUE THREAD

**Issue by tomjaguarpaw** [agrafix/Spock#164]
Spock hasn't had an update to its repository in 15 months and I'm wondering what the status of the project is.  In particular I think it would be helpful to potential users if the status was announced prominently in the README, perhaps along the lines of one of these:

* Development work on Spock has slowed down but the library is still widely used and fully supported.

* Development work on Spock has stopped but the last release is still fully functional.  Feel free to use it, although we may not get around to adding new features.

* Development work on Spock has stopped but the last release is still fully functional.  Feel free to use it, although we may not be able to fix any newly-discovered bugs.

* Development work on Spock has stopped and we recommend that you do not use it.  You might want to consider ... or ... instead.

Clarity around the status of the project would be a good contribution to the state of the Haskell ecosystem, I think.

**Comment by agrafix** [comment]
Good call! Sorry for the delay -- I've updated the project to build with a recent GHC & Stack version. If anyone is interested in helping out as a maintainer, please let me know.
