### ISSUE TITLE
release Spock-core, etc. to support ghc 9.2?

### ISSUE THREAD

**Issue by jberryman** [agrafix/Spock#178]
We're trying to upgrade to ghc 9.2 and using efc06e4b4e91f63579d04eb15ec850cf7a5ebccf in cabal.package

The full set of stuff in cabal.project to support 9.2 is:

```
-- Originally tested with: https://github.com/awjchen/superbuffer/commit/3c6fbf3da424f74156614978b3a7b51be97e27fc
-- See also: https://github.com/agrafix/superbuffer/pull/3
allow-newer: superbuffer:bytestring, superbuffer:HTF, superbuffer:QuickCheck

-- This is an unreleased version of "hvect"
source-repository-package
  type: git
  location: https://github.com/agrafix/hvect
  tag: 7736486e5789a2d56d6da72e2f4eb3a96f7b5931

-- This is an unreleased version of "Spock-core"
source-repository-package
  type: git
  location: https://github.com/agrafix/Spock.git
  tag: efc06e4b4e91f63579d04eb15ec850cf7a5ebccf
  subdir: Spock-core

-- This is an unreleased version of "reroute-core", needed for "Spock-core"
source-repository-package
  type: git
  location: https://github.com/agrafix/Spock.git
  tag: efc06e4b4e91f63579d04eb15ec850cf7a5ebccf
  subdir: reroute

```

**Comment by agrafix** [comment]
`hvect` should already be released; also just released `superbuffer`. Will look to cut a Spock release soon too!

(any interest in becoming a maintainer? :) )

**Comment by jberryman** [comment]
> any interest in becoming a maintainer?

@agrafix yes I think so! We use spock at work (hasura.io) and I would be happy to try to get bug fixes merged and try to keep spock up to date with latest package releases as part of my work.

**Comment by agrafix** [comment]
Awesome; I added you to all the relevant repos (lmk if I missed any!). Do you also want to send me your hackage username for uploads?

**Comment by jberryman** [comment]
Thanks @agrafix ! https://hackage.haskell.org/user/BrandonSimmons

**Comment by jberryman** [comment]
Let me know if you need a hand with `Spock-core` and `reroute`

**Comment by agrafix** [comment]
Sorry for the delay; was on vacation!

I did add you as a collaborator to all repos & on the corresponding hackage packages. Let me know if I missed anything. And yeah it would be awesome if you could cut the next set of releases :)
