### ISSUE TITLE
Support some kind of streaming

### ISSUE THREAD

**Issue by agrafix** [agrafix/Spock#18]
Support streaming of ByteStrings

**Comment by dylex** [comment]
Maybe there could be a `response : Wai.Response -> ActionT m a` to allow the user to provide whatever raw wai response they want (analogous to the existing `request`).

**Comment by agrafix** [comment]
Very nice, I like the idea! Would you like to implement it?

**Comment by dylex** [comment]
Sure. I'll give it a shot. I just started looking at Spock and it seems otherwise like just what I'm looking for, but really need to generate conduit responses. It seems this could just be done by adding an additional `ResponseBody` constructor.

**Comment by agrafix** [comment]
Great! 
Yes, that sounds like a good plan. You'd then just need to merge the status-code and already set headers into that response and pass it back to warp.

**Comment by dylex** [comment]
What about https://github.com/dylex/Spock/commit/df0091d764736064a12e208cf6cc1112c46f25af
It's a kind of more radical change to `ResponseBody`, but does end up simplifying some code.  Losing the Show and Eq instances on `ResponseState` is unfortunate, but it didn't seem like they were used.

**Comment by agrafix** [comment]
Looks good, the `Show` and `Eq` instances were only for debugging anyways. Could you send a pull request, please? :-)
