### ISSUE TITLE
Reset session TTL on each visit

### ISSUE THREAD

**Issue by agrafix** [agrafix/Spock#28]
Reset session TTL on each visit

**Comment by rabisg** [comment]
I was looking into this and the main issue I see is the type of `UserSessions` is `TVar ...`
This poses a problem that resetting requires `getCurrentTime` which is an IO operation
and thus cannot be performed within the semantics of TVar. Isn't it?

**Comment by agrafix** [comment]
Yeah, you are right. I think the correct way to do this would be creating a separate thread that pushes the current time into a TVar. Then you can access the time from all other atomically blocks in a consistent way.
