### ISSUE TITLE
Installing on ghc 7.10.1 fails

### ISSUE THREAD

**Issue by raguay** [agrafix/Spock#31]
I get this result:

cabal install spock
Resolving dependencies...
Configuring Spock-0.7.7.0...
Building Spock-0.7.7.0...
Failed to install Spock-0.7.7.0
Build log ( /Users/raguay/.cabal/logs/Spock-0.7.7.0.log ):
Configuring Spock-0.7.7.0...
Building Spock-0.7.7.0...
Preprocessing library Spock-0.7.7.0...
[ 1 of 10] Compiling Web.Spock.Internal.Wire ( src/Web/Spock/Internal/Wire.hs, dist/build/Web/Spock/Internal/Wire.o )

src/Web/Spock/Internal/Wire.hs:16:1: Warning:
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead

src/Web/Spock/Internal/Wire.hs:83:10: Warning:
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

src/Web/Spock/Internal/Wire.hs:83:10: Warning:
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

src/Web/Spock/Internal/Wire.hs:88:31: Warning:
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

src/Web/Spock/Internal/Wire.hs:188:21: Warning:
    In the use of ‘runErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[ 2 of 10] Compiling Web.Spock.Internal.Util ( src/Web/Spock/Internal/Util.hs, dist/build/Web/Spock/Internal/Util.o )
[ 3 of 10] Compiling Web.Spock.Internal.CoreAction ( src/Web/Spock/Internal/CoreAction.hs, dist/build/Web/Spock/Internal/CoreAction.o )

src/Web/Spock/Internal/CoreAction.hs:204:39:
    Ambiguous occurrence ‘defaultTimeLocale’
    It could refer to either ‘Data.Time.defaultTimeLocale’,
                             imported from ‘Data.Time’ at src/Web/Spock/Internal/CoreAction.hs:26:1-16
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.defaultTimeLocale’,
                             imported from ‘System.Locale’ at src/Web/Spock/Internal/CoreAction.hs:30:1-20
cabal: Error: some packages failed to install:
Spock-0.7.7.0 failed during the building phase. The exception was:
ExitFailure 1

I am running ghc 7.10.1 on a Macbook Air OS X 10.10.3.

**Comment by dnhgff** [comment]
this was fixed by pr #29 , there just hasn't been a hackage release yet :P

**Comment by agrafix** [comment]
I'll cut a release as soon as possible, I just want to get rid of all warnings first.

**Comment by elfeck** [comment]
the "new" 7.10.1 ghc version also breaks wai-middleware-static b/c of the filepath requirement. Does someone know how to work around that?

**Comment by agrafix** [comment]
Just uploaded [Version 0.7.8.0](http://hackage.haskell.org/package/Spock-0.7.8.0) with GHC7.10 support :-)

**Comment by agrafix** [comment]
You will have to ping @xich to apply the pull request @elfeck ( https://github.com/scotty-web/wai-middleware-static/pull/5 )
