### ISSUE TITLE
Webframework but homepage not served over https (by default)?

### ISSUE THREAD

**Issue by Profpatsch** [agrafix/Spock#33]
oO

**Comment by aemxdp** [comment]
Dunno what OP means, but when viewing https://www.spock.li/ some images are failing to load with error like "Mixed Content: The page at '...' was loaded over HTTPS, but requested an insecure stylesheet 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS".

**Comment by Profpatsch** [comment]
Ha, I’m sorry, sometimes I confuse languages. It took me three glances right now to notice that I wrote it in German. :P

**Comment by agrafix** [comment]
The first and most important step would be to move to signed haskell packages and/or https hackage downloads. 

I don't think you can use SSL for github-pages with a custom domain w/o a service provider like cloudflare... ( https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/ ) Any ideas?

**Comment by agrafix** [comment]
Now available via SSL: https://www.spock.li
