### ISSUE TITLE
Future Development(s)

### ISSUE THREAD

**Issue by JulianLeviston** [agrafix/Spock#40]
I wish this project could eventually become something like luminous in clojure. Do we have all the parts yet for haskell development to work like this?

http://www.luminusweb.net/

Is that the direction you have in mind for this project, or is it more likely to just be kept small, as something like sinatra?

I should mention - the microlibraries in the clojure(/script) ecosystem that allow us to end up with a full stack are outlined here: 

http://www.luminusweb.net/docs/useful_libraries.md

**Comment by agrafix** [comment]
Could you elaborate a little bit more what exactly you'd like to see added to Spock? From quickly scanning the luminusweb project page it seems to me that a many features of it can already be achieved using other libraries from hackage (e.g. html templating: blaze or lucid).

**Comment by JulianLeviston** [comment]
My apologies! There seem to be many things that are missing from the Haskell web development story. However, I'm probably just not aware of them. This is, in some ways, what luminus is about - bringing all of the disparate libraries together to form a cohesive whole with good defaults that can easily be swapped out on preference.

In particluar: 
- Something like enlive, hiccup, reagent and freactive for templating and client-side code
- Something like figwheel (live coding - aka you save the source, it recompiles and the page auto-reloads, and it can be hot-swap programmed from within the environment itself - I think yesod does this to a degree, but it doesn't have a front-end story, and is more simply auto-reloading the page). Figwheel actually loads the code around the data, which makes programming web apps amazingly fast. https://github.com/bhauman/lein-figwheel
- Server mail client
- Some kind of way to talk to SQL DBMS's easily similarly to ActiveRecord (but obviously not object-oriented). The reification of relationships and complex association-loading through a simplified DSL is what I'm interested in. It feels a little like yesod's persistent, while good, is fairly low level and not quite as expressive as other DBMS wrappering libraries I've used/seen.
- Capable session-store library
- Database Migration library
- Something like transit for efficient transport of data between front and back end (https://github.com/cognitect/transit-cljs)
- Memcached client
- authentication and authorisation library (users, and user access)
- asset management library (for URL rewriting and asset management, minification etc.)
- csrf protection

This is the stuff that I feel like may be missing for serious modern web development. 

I'd *love* to use haskell as my server language, (it's currently in Rails, of all things), but if it's going to take me 12 months to rebuild the current functionality I have, then I would have to choose clojure.

If there is a project simiar to luminus that I'm unaware of in the Haskell world, please do send me there. I've been learning and lurking around the Haskell ecosystem for at least a year now but I haven't encountered any such comprehensive project. This *was* the story with Clojure/clojurescript for a long while, too, until a the luminus folk amalgamated them all into the one project with a set of good defaults - using a template with the build tool leiningen. Also, there were a bunch of others who made headway in exposing good ways to do standard things. The pieces didn't really all exist fully until about a year or two ago.

**Comment by JulianLeviston** [comment]
@agrafix is this a silly question? It's obviously WAY more involved than your micro web app framework, but the question remains - are there answers to all of these questions already, or do people who want these things generally roll their own? I should probably just close this issue as it's not entirely relevant to this project, I'd wager?

**Comment by dnhgff** [comment]
@JulianLeviston you would probably be better served asking this kind of question on reddit.com/r/haskell or stackoverflow. i think what you are asking is more "what are the tools available for these things, and how do i stick them together to get the same kind of cohesive environment as this one"

i have not used the project you point to, but a cursory browse over your list of wanted functionality seems to all be there on hackage. i agree the community could do something better for advertising these things, maybe you can instigate some form of documentation the community has not already performed

**Comment by agrafix** [comment]
@JulianLeviston I agree with @dnhgff , much of the functionality you are asking about already exists on hackage. Just a few examples (some of them mentioned in "works great with" on http://spock.li) :

* Transit: https://github.com/jstepien/transit
* Memcached client: https://hackage.haskell.org/package/memcache
* Database handeling: https://hackage.haskell.org/package/persistent
* Templating: https://hackage.haskell.org/package/blaze-html https://hackage.haskell.org/package/lucid https://hackage.haskell.org/package/heist https://hackage.haskell.org/package/shakespeare 
* Haskell 2 JavaScript: GHCJS with https://github.com/meiersi/blaze-react
* CSRF Protection: built into Spock with SafeActions
* Users library: https://hackage.haskell.org/package/users
* Forms: https://hackage.haskell.org/package/digestive-functors 

Most should be fairly easy to integrate into Spock. If not let me know!

**Comment by JulianLeviston** [comment]
Excellent. Thanks for humoring me, guys. I'm aware of most of the mentioned packages, but I'll ask elsewhere.
