### ISSUE TITLE
Aeson 0.6.2.1 causes "jsonBody" to fail

### ISSUE THREAD

**Issue by sportanova** [agrafix/Spock#41]
Correct json will return Left "incomplete input". Related to https://github.com/bos/aeson/issues/142

As a workaround I upgraded Aeson to 0.7.0.0 and am using "A.eitherDecodeStrict", which is the underlying function that jsonBody uses.

How tough would it be to upgrade the version of Aeson? I could try to take a crack at a pull request

**Comment by agrafix** [comment]
I think we can safely bump the constraint to 0.7.

**Comment by sportanova** [comment]
nice, thanks!
