### ISSUE TITLE
Problem with cookies

### ISSUE THREAD

**Issue by eriksvedang** [agrafix/Spock#42]
Having a blast with Spock but I've run into a problem that I can't figure out.

When setting cookies this works well:
```haskell
do setCookie "username" username 3600
```
But when I add a html response afterwards (or another 'setCookie') the cookie is never set:
```haskell
do setCookie "username" username 3600
   html "yup"
```

Any idea why this is?

**Comment by agrafix** [comment]
I've tried to reproduce this (with Spock-0.7.10.0, 0.7.11 and 0.7.12 only include minor changes), but for me everything works fine:

```haskell
runExample :: IO ()
runExample =
    runSpock 4000 $
    spockT id $
    do get "set-cookie" $
           do setCookie "username" "cool" 3600
              html "Cookie is set"
       get "is-cookie-set" $
           do m <- cookie "username"
              html (if m == Just "cool" then "ok" else "failed")
```

http://localhost:4000/set-cookie
-> "Cookie is set"

http://localhost:4000/is-cookie-set
-> "ok"

**Comment by agrafix** [comment]
Should be fixed in 2af7dff5c55ed5e3acecd320620017268a7cfede

**Comment by eriksvedang** [comment]
OK, awesome! Thanks!!! How can I get this patch, do I have to build from source? When will it be on Hackage?

**Comment by eriksvedang** [comment]
It would be great if this fix comes up on Hackage since I can't push the project to Heroku right now, they only handle version 0.7.12.0. What's the plan for the 0.8.0.0 release?

**Comment by agrafix** [comment]
I'll release 0.8.0.0 today.

**Comment by agrafix** [comment]
It's now up on hackage, looking forward to your feedback! :-) http://hackage.haskell.org/package/Spock-0.8.0.0

**Comment by eriksvedang** [comment]
Works perfectly now, thanks for the quick responses! The framework is great, will keep filing things I find.
