### ISSUE TITLE
Token Based Authentication

### ISSUE THREAD

**Issue by qmmdb** [agrafix/Spock#47]
Have you considered adding token based authentication?

**Comment by agrafix** [comment]
Yes, that is certainly a good addition! But it will not land in the `Spock` package, but rather in a separate package (maybe it fits into the `users` package?). What exact type of token based auth did you have in mind? API-Keys? Cookie-Tokens? OAuth?

**Comment by qmmdb** [comment]
I'm leading toward an Authorization Server to issue access tokens (JWT format) to client applications.

**Comment by agrafix** [comment]
Yes, that should be a perfect case for an independent package building on Spock, as I do not see where it actually needs the Spock internals. There's a JWT library for haskell (https://github.com/frasertweedale/hs-jose), so it should be quick to implement. Do you want to give it a shot? :-)

**Comment by qmmdb** [comment]
1. I've never had to deal with this before until this week.
2. I'm reading all I can about the OAuth.
3. I really don't know if I'm the person to do this.

Not to kill any conversation, but since I opened this in the wrong repo, I'll close it now.

**Comment by qmmdb** [comment]
BTW, thanks for all of your work. This is an amazing project that has me excited about development in Haskell again :)

**Comment by agrafix** [comment]
Happy to hear that! :-) I can't promise anything because I am very busy atm, but I'll look into OAuth & co when I find time. Let me know if you have any other ideas for Spock, find a bug or a bad documented feature!

**Comment by qmmdb** [comment]
https://github.com/anchor/oauth2-server seems relevant
