### ISSUE TITLE
Custom 404 pages.

### ISSUE THREAD

**Issue by ak3n** [agrafix/Spock#51]
It would be nice to have custom 404 pages.

**Comment by agrafix** [comment]
You can achieve this using hookAny, but it makes sense to make this configurable, too, so I will leave the issue opened for now.

**Comment by Inaimathi** [comment]
@agrafix - is there an example of using `hookAny` in this way somewhere?

**Comment by ak3n** [comment]
@Inaimathi maybe you can find it helpful: https://github.com/ak3n/pubsy/blob/master/webapp/src/PubSy.hs#L100

**Comment by agrafix** [comment]
Notes. 

```haskell
data SpockConfig
    = SpockConfig
    { sc_maxRequestSize :: Maybe Int64
    , sc_errorHandler :: Status -> ActionCtx ctx m ()
    }

makeFallbackApp :: Status -> (Status -> ActionCtx ctx m ()) -> IO Wai.Application
makeFallbackApp status errorHandler =
    spockAsApp $ spockT id (hookAny $ errorHandler status)

-- 404 --> 500
```
