### ISSUE TITLE
spock.li looks bad on iPad mini

### ISSUE THREAD

**Issue by roshats** [agrafix/Spock#53]
On iPad mini https://www.spock.li looks like this:
![img_2051_2](https://cloud.githubusercontent.com/assets/434466/10268710/eab0ac42-6ac9-11e5-8d83-f041529650b2.png)

**Comment by agrafix** [comment]
@folsen did most of the homepage design, do you have ideas? It might be enough to add the bootstrap class `img-responsive` to the image?

**Comment by folsen** [comment]
@agrafix yeah, i wonder what's up here, if I recall correctly I tested on iPhone, but perhaps iPad mini is somewhere in-between in sizes. I might have time to check it out during the weekend!

**Comment by roshats** [comment]
@agrafix, @folsen I think that the problem is
```
@media (min-width: 768px)
.container {
    width: 900px;
}
```

**Comment by roshats** [comment]
Fixed.
