### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by elfeck** [agrafix/Spock#60]
Hi,
I was wondering if there is TLS support in spock already/planned? Some of the websites built with spock (by agrafix) have https but I could not find anything in the spock package itself.
Thanks!

**Comment by agrafix** [comment]
You can convert a Spock Application using `spockAsApp` to an `Application` and then use [warp-tls](https://hackage.haskell.org/package/warp-tls-3.1.4/docs/Network-Wai-Handler-WarpTLS.html) `runTLS` to execute it

**Comment by elfeck** [comment]
Ah, okay thanks!
