### ISSUE TITLE
Custom http verb for routes (NOTIFY)

### ISSUE THREAD

**Issue by merc1031** [agrafix/Spock#61]
I am trying to interface with a upnp callback protocol and it seems to be making a NOTIFY request.
How can i capture this route.
It seems there is no way to use a route outside of the StdMethod type.

Thanks

**Comment by agrafix** [comment]
Currently Spock does not provide support for custom http verbs. Basically, these are the responsible lines for that: https://github.com/agrafix/Spock/blob/master/src/Web/Spock/Internal/Wire.hs#L404-L410 . Would you be interested in giving it a shot with a pull request? If yes I'd be happy to look at your design and then review and merge your pull request :-)
