### ISSUE TITLE
How does files/UploadedFile work

### ISSUE THREAD

**Issue by elfeck** [agrafix/Spock#66]
Hi,

I am wondering how ```files``` and ```UploadedFile``` work, especially, where the files "/tmp/webenXXXX.buf" is stored in the filesystem.
I was trying to decipher the src in Spock but it I don't have a lot of knowledge of WAI. Can someone explain/point me to the right doc or src if no doc is available?

Thanks!

**Comment by agrafix** [comment]
The uploaded files are handled here: https://github.com/agrafix/Spock/blob/c13fc9bcade9afe11b008a1c20d9498bcee34d7b/src/Web/Spock/Internal/Wire.hs#L266 using the https://hackage.haskell.org/package/wai-extra-3.0.13/docs/Network-Wai-Parse.html package and the `tempFileBackend`.

**Comment by elfeck** [comment]
Ah okay. So it seems that WAI uses ```getTemporaryDirectory``` from ```System.Directory```. But I can't find the temporary file which is supposed to be there. Any idea why?

**Comment by agrafix** [comment]
The file will only live while the request is being processed and removed shortly after.

**Comment by elfeck** [comment]
Is the file then hold in-memory or does it get moved somewhere else?

**Comment by agrafix** [comment]
No, it's your responsibility to persist the file by copying it to a different location.

**Comment by elfeck** [comment]
Okay, so after I call ```files```, I need to deal with it or else it vanishes. Makes sense. You can close this issue this is correct. Thanks for your help!

**Comment by agrafix** [comment]
No worries, glad I could help!
