### ISSUE TITLE
Mailing list, newsgroup, or bulletin board forum for Spock?

### ISSUE THREAD

**Issue by tiennao** [agrafix/Spock#68]
I find Spock a very elegant and well designed framework that leverages Haskell very well. As someone fairly new to the Haskell language---and to web programming in general---I have lots of questions. Is there a mailing list, a news group, or forum to discuss Spock? Or can one be created for it?

There's so much to learn and discover, and I think I can get faster if there were more support for newcomers.

**Comment by agrafix** [comment]
I've recently created haskell-spock@googlegroups.com , but I haven't put the word out about it yet. I think that would be a great place to start and then see what's needed on top of it.
