### ISSUE TITLE
Submit to TechEmpower benchmarks

### ISSUE THREAD

**Issue by chris-kahn** [agrafix/Spock#69]
I saw some benchmarks against a few other Haskell frameworks, but it might be a good idea to submit something to the TechEmpower benchmarks, both to compare Spock against non-Haskell frameworks and also to get Spock more visibility.

**Comment by agrafix** [comment]
Sorry for the late reply; this is a great idea! Would you like to give this a shot? @kanadskiy

**Comment by Rydgel** [comment]
It might be way to do more examples for documentation too. IIRC the benchmark itself is not very complicated. I might give it a try if I can spare some time.

**Comment by agrafix** [comment]
Sounds great, thank you!

**Comment by Rydgel** [comment]
Started working on it: https://github.com/Rydgel/FrameworkBenchmarks/tree/master/frameworks/Haskell/spock

**Comment by agrafix** [comment]
Nice! Let me know when it's ready @Rydgel

**Comment by Rydgel** [comment]
Alright, the code is done, you can start to look at it [here](https://github.com/Rydgel/FrameworkBenchmarks/tree/master/frameworks/Haskell/spock).

Now I just need to prepare some config files to wire that with the techempower stuff, and test it.

**Comment by agrafix** [comment]
Thanks, looks great! Three suggestions:

* add bang patterns to all fields in the models to make sure that there are not thunks laying around
* add inline annotations to all the functions and instance methods in `Models.*`
* switch to `aeson-0.11` to use `toEncoding` instead of `toJSON`, to skip intermediate `Value`s.

**Comment by Rydgel** [comment]
@agrafix done!

**Comment by agrafix** [comment]
Cool! What do we have to do to make a submission? You probably have to send a PR?

**Comment by Rydgel** [comment]
Yeah, a PR will do. Something like [this](https://github.com/TechEmpower/FrameworkBenchmarks/pull/39).

I'm currently configuring stuff to actually run the benchmark inside their project.

**Comment by agrafix** [comment]
Okay, let me know if I can help with something.

**Comment by Rydgel** [comment]
I will share the local results of the bench here before submitting.

**Comment by Rydgel** [comment]
@agrafix 
It seems I am unable to send only
`Content-Type:text/plain`
instead of
`Content-Type:text/plain; charset=utf-8`

I used `setHeader` but does `json` or `text` overrides this?

Also it seems that Spock set a cookie, is this by default, can I disable it?

**Comment by agrafix** [comment]
Correct, the content type is overridden. Maybe we should change this to only set the Content-Type if it's not already set. 

If you don't use connection pooling as provided by Spock, but roll your own connection pooling (which is pretty easy with the `resource-pool` package), then you can use `spockT` instead of Spock and skip all the session management. I'm planning to make this easier with the default `spock` setup, too, but it's not there yet.

**Comment by Rydgel** [comment]
Managed to get the bench working, and performance seems pretty good so far.

**Comment by Rydgel** [comment]
My local results. Keep in mind this was run inside a virtual machine.

[bench.zip](https://github.com/agrafix/Spock/files/152463/bench.zip)

**Comment by Rydgel** [comment]
I made a few optimizations.
But I wonder if there is a better way of doing those X independent queries. Right now I'm using `mapConcurrently`. But maybe something with a more fined-grained control will provide better performances.
I admit I don't have a lot of experiences in that domain in Haskell.

**Comment by agrafix** [comment]
You're reusing the same connection for all concurrent actions. It might be better to use an independent connection from the connection pool for each of those concurrent actions.

**Comment by Rydgel** [comment]
@agrafix is `runQuery` the only way for me to get a connection from the Pool?

**Comment by agrafix** [comment]
You'd have to create the pool by hand:

```haskell
do pool <- createPool (cb_createConn cb) (cb_destroyConn cb)
                        (pc_stripes pc) (pc_keepOpenTime pc)
                        (pc_resPerStripe pc)
```

Inject it into Spock with `PCPool` for the other actions, but then use it directly in mapConcurrently:

```haskell
mapConcurrently (withResource pool $ \conn -> ....) 
```

**Comment by Rydgel** [comment]
Doing 500 requests in 80ms feels good man.

**Comment by agrafix** [comment]
Okay! Maybe submitting this to reddit and ask for further performance improvements could help?

**Comment by Rydgel** [comment]
Why not, /r/haskell? Or does spock have its own?

**Comment by agrafix** [comment]
/r/haskell should be good, spock doesn't have its own at the moment and in practice we are benchmarking Spock+wai, so it should be interesting for non-spock users too.

**Comment by agrafix** [comment]
@Rydgel do you want to post this or should I take care of that?

**Comment by Rydgel** [comment]
Kind of busy at the moment Alex. Feel free to do it.

If you can't I'll probably do it tonight.

Sent from iPhone

Linux, web 2.0 -> http://phollow.fr

**Comment by Rydgel** [comment]
Submitted: https://www.reddit.com/r/haskell/comments/48wtc9/spock_framework_submission_to_the_techempower_web/

**Comment by agrafix** [comment]
Any updates on this @Rydgel ? :-)

**Comment by Rydgel** [comment]
@agrafix it has been submitted and merged back to the main repo :)
https://github.com/TechEmpower/FrameworkBenchmarks/pull/1954

**Comment by agrafix** [comment]
Perfect! Thanks a lot for your work!!

**Comment by flip111** [comment]
I tried to upgrade this to lts-10.0

After removing `import Web.Spock.Safe` (removed since spock 0.11) i got the following errors:

```
Setup spock: [4 of 4] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/spock-exe/spock-exe-tmp/Main.o )
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:35:12: error:
Setup spock:     Not in scope: type constructor or class `PoolCfg'
Setup spock:    |
Setup spock: 35 | poolCfg :: PoolCfg
Setup spock:    |            ^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:38:11: error:
Setup spock:     Not in scope: type constructor or class `ConnBuilder'
Setup spock:    |
Setup spock: 38 | pcconn :: ConnBuilder PG.Connection
Setup spock:    |           ^^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:41:11: error:
Setup spock:     Not in scope: type constructor or class `PoolOrConn'
Setup spock:    |
Setup spock: 41 | dbConn :: PoolOrConn PG.Connection
Setup spock:    |           ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:45:33: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 45 | blaze :: MonadIO m => H.Html -> ActionCtxT ctx m a
Setup spock:    |                                 ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:52:34: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 52 | getQueriesNumber :: MonadIO m => ActionCtxT ctx m Int
Setup spock:    |                                  ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:60:23: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 60 | test1 :: MonadIO m => ActionCtxT ctx m a
Setup spock:    |                       ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:67:10: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 67 | test2 :: ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |          ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:67:26: error:
Setup spock:     Not in scope: type constructor or class `WebStateM'
Setup spock:    |
Setup spock: 67 | test2 :: ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |                          ^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:77:32: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 77 | test3 :: Pool PG.Connection -> ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |                                ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:77:48: error:
Setup spock:     Not in scope: type constructor or class `WebStateM'
Setup spock:    |
Setup spock: 77 | test3 :: Pool PG.Connection -> ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |                                                ^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:86:10: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 86 | test4 :: ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |          ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:86:26: error:
Setup spock:     Not in scope: type constructor or class `WebStateM'
Setup spock:    |
Setup spock: 86 | test4 :: ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |                          ^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:95:32: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:    |
Setup spock: 95 | test5 :: Pool PG.Connection -> ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |                                ^^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:95:48: error:
Setup spock:     Not in scope: type constructor or class `WebStateM'
Setup spock:    |
Setup spock: 95 | test5 :: Pool PG.Connection -> ActionCtxT ctx (WebStateM PG.Connection b ()) a
Setup spock:    |                                                ^^^^^^^^^
Setup spock: 
Setup spock: /home/vagrant/FrameworkBenchmarks/frameworks/Haskell/spock/src/Main.hs:105:23: error:
Setup spock:     Not in scope: type constructor or class `ActionCtxT'
Setup spock:     |
Setup spock: 105 | test6 :: MonadIO m => ActionCtxT ctx m a
Setup spock:     |                       ^^^^^^^^^^
Setup spock: 
Setup spock: --  While building custom Setup.hs for package spock-0.1.0.0 using:
Setup spock:       /home/vagrant/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.1.0 build exe:spock-exe --ghc-options " -ddump-hi -ddump-to-file"
Setup spock:     Process exited with code: ExitFailure 1
```

I'm posting in this issue to keep track of the TFB code.
