### ISSUE TITLE
No cookies Function

### ISSUE THREAD

**Issue by aspidites** [agrafix/Spock#72]
So I have a way to get a specific cookie by name, but none to get all cookies. I'd expect it to either return a (Map Text Text) or a [(Text Text)]. I was attempting to convert a service we have written in [Flask](http://flask.pocoo.org/) which serializes all cookies and does some other stuff with them. Without this functionality, I'm not able to convert the service.

**Comment by aspidites** [comment]
Maybe something less ugly than:

```haskell
cookies :: MonadIO m => ActionCtxT ctx m [(Text, Text)]
cookies = do
  req <- request
  let c = parseCookies <$> lookup "cookie" (Wai.requestHeaders req)
  case c of
    Nothing -> return []
    (Just c') -> return c'

```

**Comment by agrafix** [comment]
I'll look into this
