### ISSUE TITLE
crash in clearAllSessions and impossible to disconnect users

### ISSUE THREAD

**Issue by VincentSe** [agrafix/Spock#78]
Hi,
I'm using Spock on Windows and it crashes when I call clearAllSessions at line 144 of SessionManager.hs.

Also I don't manage to disconnect a user with sessionRegenerateId. Subsequent calls to withBasicAuthData still arrive with the previous username and password. When I delete the cookies on the browser side, withBasicAuthData then comes with Nothing as its argument.

Thanks,
Vincent

**Comment by agrafix** [comment]
Hi,

* clearAllSessions: that sounds pretty bad. Does the test suite pass on your machine?

* sessionRegenerateId: This will not disconnect a user, it will keep the current session state but assign the user a new session id and invalidate the old one. (prevents [session fixation attacks](https://en.wikipedia.org/wiki/Session_fixation) )

* withBasicAuthData: This is independent from sessions, it only implements the server side part for [Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication)

If you want to logout a user, you could (as in "easiest thing to do") store a "bool" (`data IsLoggedIn = LoggedIn | LoggedOut`) as session state and then change that after login/logout and check the state on every request (using `prehook`s for example)

**Comment by VincentSe** [comment]
How do I run the tests (I'm a haskell beginner) ?

My mistake for the authentication. By reading the HTTP headers I saw that Internet Explorer is actually storing my password the first time, then resending it automatically. All this without warning.

I understand now that I will have to implement authentication in the session's state. However getSessionId forces me to use type SessionCfg a, where the only freedom I have is the underlying type a. This type a is given by sc_emptySession, which sounds weird if I start writing information to it (modifySession) : it's no longer empty.

Or there is another way to define and access the session's state ?

**Comment by agrafix** [comment]
You'd `git clone` the Spock repository, then checkout the correct tag (the same as the package version of Spock you are using). Then run `stack test` in the directory.

I don't fully understand your question, but I hope this will help:

* when an "unknown" Visitor accesses your Site, she/he will get an empty session (-> Value provided in `sc_emptySession`.)
* You can then read or modify the session according to your application.

So if you just want a basic login, then you could set `sc_emptySession` to `LoggedOut` (from my `isLoggedIn` type above) and then after a succesfull login you could set it to `LoggedIn`.

**Comment by VincentSe** [comment]
I did cabal unpack spock and it downloaded the source code in a new folder called Spock-0.10.0.1. Then I went into this folder, ran stack test, and got :

Run from outside a project, using implicit global project config
TlsExceptionHostPort (HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 72\nFrom:\theader\n\n")) "www.stackage.org" 443

Setting the session like this solves my authentication :
    modifySession (\sess -> sess{sc_emptySession = LoggedIn})
however I find it weird to call it sc_emptySession when it has the LoggedIn information inside. It's no longer empty.

**Comment by agrafix** [comment]
I think the stack.yaml file is not included in the package from Hackage, so it would be a good idea to pull it via github. The error should not happen. That's an issue with stack. Maybe create a bug report there?

I don't unterstand, usually modifySession does not operate on SessionCfg. The would mean you have a SessionCfg inside your SessionCfg. What's the main type of your application?

**Comment by VincentSe** [comment]
I changed to a linux machine and downloaded the repo from git. The test suite passes, but it still crashes on clearAllSessions.

For the authentication you were right, I ended up with a SessionCfg inside a SessionCfg. I don't really understand how I got there, but after cleaning this up I have a working server. Thanks !

**Comment by agrafix** [comment]
Would you like to contribute a test case demonstrating the crash?

**Comment by agrafix** [comment]
It's actually not too easy to write a test here on the `SessionManager` level :-( I'm looking into this.
