### ISSUE TITLE
Connection pool examples

### ISSUE THREAD

**Issue by sqd** [agrafix/Spock#85]
I want to use Spock's connection pooling, but I'm not sure how it works.

I have code looks like this:

```haskell
config = defaultSpockCfg () (PCConn $ ConnBuillder connectDB closeDB poolConfig) () where
    poolConfig = PoolCfg 2 5 300

main = runSpock 80 $ spock config $ do
    get root $ do
        -- runQuery, I suppose? But the types don't fit.
        result <- some_query
        text $ foo result
```
How should I make it work? Could we have some examples?

**Comment by agrafix** [comment]
What's the type signature of `connectDB`? What database library are you using? `runQuery` is the correct approach, it selects one resource/connection and returns it for you to run your database action on.

**Comment by sqd** [comment]
`connectDB :: IO Pipe` as it's specified in [ConnBuilder](https://hackage.haskell.org/package/Spock-0.10.0.1/docs/Web-Spock-Shared.html#t:ConnBuilder) (`Pipe` is mongoDB's connection). But `ActionCtxT` doesn't have `HasSpock` instance. Does it mean that I have to write my logic in the routing part?

**Comment by agrafix** [comment]
No, if you are using `spock` to define your routes, you should be running in `SpockActionCtx ctx conn sess st` which has a `HasSpock` instance.

**Comment by sqd** [comment]
Oh, now I see. Thanks!
