### ISSUE TITLE
Params into list of key value pair

### ISSUE THREAD

**Issue by WongKamFu** [agrafix/Spock#87]
Hi is there any function I could use to get something like [(foo,bar),(baz,qux)] from
http://localhost/?params=foo=bar,baz=qux
I took a look at [params](https://hackage.haskell.org/package/Spock-0.10.0.1/docs/src/Web-Spock-Internal-CoreAction.html#params), but I don't think it's the right function for my need.

**Comment by agrafix** [comment]
You are right `params` will return a superset of what you are looking for. Would you like to add a function? You would probably have to split the handling of the variables in 

https://github.com/agrafix/Spock/blob/7739eef07f4feaf993c10ef0008dfc00ffd00449/Spock-core/src/Web/Spock/Internal/Wire.hs#L271

**Comment by WongKamFu** [comment]
Okay, got it. Thanks for the pointer!

**Comment by WongKamFu** [comment]
Since you're re-opening this, maybe it's better to share what I have done so far.

On my controller:

```
get (var <//> "update") $ \guid -> do
    rawParams <- param' "params"
    let listOfKeyValueParams = splitRawParamsToPairsOfKeyAndValue $ Data.Text.unpack rawParams
    ....

splitRawParamsToPairsOfKeyAndValue :: String -> Maybe [(String, String)]   
splitRawParamsToPairsOfKeyAndValue a =
   -- simply drop the process if we detect a missing value
   if odd(Data.List.length $ paramList a)
      then Nothing
      else
         Just $ Data.List.map (\[x,y] -> (x, y)) . Data.List.Split.chunksOf 2 $ paramToList a

   where
      paramToList :: String -> [String]
      paramToList = Data.List.Split.splitOneOf ",="
```

As @agrafix pointed before, what I need to do is just split the params.

**Comment by agrafix** [comment]
Ah! I did not read your request correctly. I thought you where looking to parse `http://localhost/?foo=bar&baz=qux` into `[(foo,bar),(baz,qux)]`?

**Comment by WongKamFu** [comment]
That'd be okay too, since (from the user point of view) the difference is only the delimiter.
At the moment, I only do tokenization.
