### ISSUE TITLE
Stack Template

### ISSUE THREAD

**Issue by joehillen** [agrafix/Spock#92]
It would be nice if there was a [stack-template](https://github.com/commercialhaskell/stack-templates) for spock. Then starting a new project would be as easy as `stack new myproject spock`

 There already are templates for scotty and yesod.

**Comment by agrafix** [comment]
Yes, sounds like a good idea! Would you be interested in making a proposal here how the template should look like?

**Comment by jturner** [comment]
I just submitted a pull request adding a spock stack template.

https://github.com/commercialhaskell/stack-templates/pull/74

**Comment by agrafix** [comment]
@jturner any news on this? It looks like we're waiting for the PR to merge?

**Comment by jturner** [comment]
@agrafix nothing yet. I pinged the PR, not sure if that will trigger anything tho.

**Comment by agrafix** [comment]
Looks merged now :-) Thanks!
