### ISSUE TITLE
Strictness in API data types

### ISSUE THREAD

**Issue by elfeck** [agrafix/Spock#96]
Hello,

I've been toying with the API example [on sppock.li](https://www.spock.li/2016/08/25/shareable-apis.html) and noticed that all data types used in the API definition are strict (i.e. `!T.Text` or `!User`). Why is strictness used here? Is it necessary?

Thanks!

**Comment by agrafix** [comment]
I have made it my personal convention to make all data types strict except there is an explicit reason to make them lazy. This helps preventing space leaks to some extent, but is not strictly required in the example given.

**Comment by agrafix** [comment]
Please feel free to email me if you have more questions ;-)
