### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [agrafix/Spock#97]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by agrafix** [comment]
The full documentation is always available as linked from the homepage or the readme: https://spockdocs.s3.eu-central-1.amazonaws.com/index.html . I will also try to upload then manually to hackage.

**Comment by expipiplus1** [comment]
Thanks

**Comment by agrafix** [comment]
This is now resolved
