### ISSUE TITLE
Testing with session

### ISSUE THREAD

**Issue by zjhmale** [agrafix/Spock#99]
Hi @agrafix, When I try to test an API actually needs the session, it will fail since the mock server can not reach the in-memory session. For instance, when testing with [this test case](https://github.com/zjhmale/HAS/blob/master/spock-todo/test/AppSpec.hs#L34), it will produce the error message:

![image](https://cloud.githubusercontent.com/assets/6234553/20468247/a73ebcfa-afcf-11e6-93d7-04e3d27a49af.png)

Which is defined [here](https://github.com/zjhmale/HAS/blob/master/spock-todo/src/Route.hs#L30), and it proves that the mock app can not reach out to the session when testing it, but it works fine when I start the server and test the API by hand.

Any ideas to fix this? Thanks in advance!

**Comment by agrafix** [comment]
I think the testing framework does not automatically manage cookies for you. So you'll need to read and then set the cookies by hand :-/

**Comment by zjhmale** [comment]
@agrafix, Thanks for the hint! But after I using `setCookie` in `login` action, I still can not read cookie in `post` action.

Here is the code snippet.

```Haskell
post "login" $ do
      c <- cookie "todo"
      liftIO $ print c
      setCookie "todo" "HczlBC9LOI9jyi9lhZ4Yj8YZLG9WmW31nJ01DzPKw-h9SRVsx3JhLRT-Kaid9DLnh3EsxvH04RDDiKj3hP_Y7g" defaultCookieSettings { cs_EOL = CookieValidFor 3600 }
      username <- param' "username"
      password <- param' "password"
      _type <- param' "type"
      (j, sess) <- runQuery' $ loginSignupPost username password _type
      writeSession sess
      json j

post "posts" $ do
      c <- cookie "todo"
      liftIO $ print c
      requireAuth onfail $ \(uid, _) ->
        jsonBody' >>= runQuery' . newPost uid >>= json
```

If I start the server by hand, it will log out the cookie with a Just value, but in test cases, it will just get Nothing.

Is there any example projects that actually test Spock app with session and cookie? I can find one you wrote [here](https://github.com/agrafix/Spock/blob/master/Spock-core/test/Web/Spock/SafeSpec.hs#L32), but seems you did not actually test the `cookie/single` and `cookie/multiple` API.

**Comment by agrafix** [comment]
Sorry, that's not what I meant. The testing framework runs each test in it's own session, so cookies will not be preserved between the tests. (See https://github.com/hspec/hspec-wai/blob/2c09b944bc85b0d6d2f3d3807c4885b01f736c03/src/Test/Hspec/Wai/Internal.hs#L42 ). You'll either have to write your own wrapper around wai-test(-extra) and reuse the session, or extract and pass around cookies manually like in https://github.com/agrafix/Spock/blob/2c60a48b2c0be0768071cc1b3c7f14590ffcc7d6/Spock/test/Web/Spock/CsrfSpec.hs#L32-L45

**Comment by zjhmale** [comment]
Thanks! I'll follow the second solution first :)

**Comment by zjhmale** [comment]
Hi @agrafix, the second way works for me, Thanks! I'll try to figure out how to write my own hspec wrapper then.

**Comment by agrafix** [comment]
Btw: please do take a look at https://github.com/agrafix/users , I think it would be a great fit for your project :-)

**Comment by zjhmale** [comment]
@agrafix Great! I'll try to use this package tomorrow :)
